/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

/**
 *
 * @author sachi
 */
import com.lowagie.text.Section;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
public class database extends javax.swing.JPanel {

    /**
     * Creates new form D
     */
    public database() {
        initComponents();
        table_update();
        Connect();
        dt(); // daet
        
        times(); // time
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        public void dt()
    {
      Date d = new Date();
      SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MMM-dd");
      String dd =sdf.format(d);
      l_date.setText(dd);
    
    }
       
        Timer t;
        SimpleDateFormat st;
    
    
    public void times(){
      
    
       t = new Timer(0, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            //
        Date dt  =new Date();
        st = new SimpleDateFormat("hh:mm:ss a");
        
        String tt = st.format(dt);
        l_time.setText(tt);
        
        }
    });
         
       
         t.start();
       
    }
    
    
     Connection con;
     PreparedStatement pst;
     ResultSet rs;
    
     
     public void Connect()
     {
        try {
            Class.forName("com.mysql.jdbc.Driver");
                                                    
            try {
               con = (com.mysql.jdbc.Connection)DriverManager.getConnection("jdbc:mysql://localhost/simple_student","root","");
               String sql ="select id as 'ID', studentname as 'C_Name',fathername as 'F_Name',phone as 'Mobile',dateofbirth as 'Licence Issue Date',gender as 'Gender',class as 'BR_Nb',section as 'Section',admissiondate as 'Expire Date',cnic as 'NIC',email as 'Email',address as 'Adress' from student ";
               PreparedStatement pst =con.prepareStatement(sql);
               ResultSet rs =pst.executeQuery();
               jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(system.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(system.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtsname = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtgender = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsectionn = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        txtcnic = new javax.swing.JTextField();
        txtclass = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtadddate = new com.toedter.calendar.JDateChooser();
        txtdob = new com.toedter.calendar.JDateChooser();
        l_date = new javax.swing.JLabel();
        l_time = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(jTable1.getFont());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "C_Name", "F_Name", "Mobile", "DOB", "Gender", "BR nb", "Section", "Issue Date", "NIC", "Email", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 1090, 360));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Candidate Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Factory Name");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mobile Number");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Expire Date");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NIC");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtsname.setBackground(new java.awt.Color(204, 204, 204));
        txtsname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txtsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 240, -1));

        txtfname.setBackground(new java.awt.Color(204, 204, 204));
        txtfname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 240, -1));

        txtphone.setBackground(new java.awt.Color(204, 204, 204));
        txtphone.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphoneKeyTyped(evt);
            }
        });
        jPanel2.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 230, -1));

        txtemail.setBackground(new java.awt.Color(204, 204, 204));
        txtemail.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 240, -1));

        txtgender.setBackground(new java.awt.Color(204, 204, 204));
        txtgender.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel2.add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 220, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BR Nb");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 48, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Section");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        txtsectionn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtsectionn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        jPanel2.add(txtsectionn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 240, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Licence Issue Date");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email Address");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        txtaddress.setBackground(new java.awt.Color(204, 204, 204));
        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 13)); // NOI18N
        txtaddress.setRows(5);
        jScrollPane2.setViewportView(txtaddress);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 470, 60));

        txtcnic.setBackground(new java.awt.Color(204, 204, 204));
        txtcnic.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txtcnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 240, -1));

        txtclass.setBackground(new java.awt.Color(204, 204, 204));
        txtclass.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txtclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 30));
        jPanel2.add(txtadddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 230, -1));
        jPanel2.add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 220, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1090, 250));

        l_date.setBackground(new java.awt.Color(255, 255, 255));
        l_date.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        l_date.setForeground(new java.awt.Color(255, 255, 255));
        l_date.setText("0");
        add(l_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 210, 30));

        l_time.setBackground(new java.awt.Color(0, 0, 0));
        l_time.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        l_time.setForeground(new java.awt.Color(255, 255, 255));
        l_time.setText("0");
        add(l_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 220, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Update");
        jButton5.setMaximumSize(new java.awt.Dimension(51, 23));
        jButton5.setPreferredSize(new java.awt.Dimension(51, 26));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 230, 30));

        jButton6.setBackground(new java.awt.Color(204, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete");
        jButton6.setPreferredSize(new java.awt.Dimension(51, 26));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 230, 30));
    }// </editor-fold>//GEN-END:initComponents
            private void table_update()
    {      
        
        try {
            int c;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con =DriverManager.getConnection("jdbc:mysql://localhost:3306/simple_student","root","");
                pst=con.prepareStatement("select * from student");
                ResultSet rs=pst.executeQuery();
                
                ResultSetMetaData rsd=rs.getMetaData();
                c=rsd.getColumnCount();
                
                DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
                d.setRowCount(0);
                
               while(rs.next()) 
               {
                   Vector v2 = new Vector();
                   
                   for(int i=1; i<=c; i++)
                   {
                        v2.add(rs.getString("id"));
                        v2.add(rs.getString("studentname"));
                        v2.add(rs.getString("fathername"));
                        v2.add(rs.getString("phone"));
                        v2.add(rs.getString("dateofbirth"));
                        v2.add(rs.getString("gender"));
                        v2.add(rs.getString("class"));
                        v2.add(rs.getString("section"));
                        v2.add(rs.getString("admissiondate"));
                        v2.add(rs.getString("cnic"));
                        v2.add(rs.getString("email"));
                        v2.add(rs.getString("address"));
                   
                   
                   
                   
                   }
                     d.addRow(v2);
               }  
          
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(database.class.getName()).log(Level.SEVERE, null, ex);
            }
          
            
        } catch (SQLException ex) {
            Logger.getLogger(database.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Table mouse click

        // Assuming you have declared txtsname, txtfname, txtphone, txtdob, txtgender, txtclass,
        // txtsectionn, txtadddate, txtcnic, txtemail, and txtaddress earlier in your class.

        DefaultTableModel d1 = (DefaultTableModel) jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
            
        // Check if a row is selected
        if (selectIndex == -1) {
            return; // No row selected, do nothing
        }

        // Populate the Swing components with data from the selected row
        txtsname.setText(d1.getValueAt(selectIndex, 1).toString());
        txtfname.setText(d1.getValueAt(selectIndex, 2).toString());
        txtphone.setText(d1.getValueAt(selectIndex, 3).toString());

        // Assuming txtdob is a JDateChooser (date picker)
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date dob = dateFormat.parse(d1.getValueAt(selectIndex, 4).toString());
            txtdob.setDate(dob);
        } catch (ParseException ex) {
            // Handle parsing error
            ex.printStackTrace();
        }

        // Assuming txtgender is a JComboBox
        txtgender.setSelectedItem(d1.getValueAt(selectIndex, 5).toString());

        txtclass.setText(d1.getValueAt(selectIndex, 6).toString());

        // Assuming txtsectionn is a JComboBox  
        txtsectionn.setSelectedItem(d1.getValueAt(selectIndex, 7).toString());
         
        // Assuming txtadddate is a JDateChooser (date picker)
        try { 
            
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date addDate = dateFormat.parse(d1.getValueAt(selectIndex, 8).toString()); 
                txtadddate.setDate(addDate);
        }
           catch (ParseException ex) 
         { 
           
             // Handle parsing error 
            ex.printStackTrace();
         }

        txtcnic.setText(d1.getValueAt(selectIndex, 9).toString());
        txtemail.setText(d1.getValueAt(selectIndex, 10).toString());
        txtaddress.setText(d1.getValueAt(selectIndex, 11).toString());

        /*  DefaultTableModel d1=(DefaultTableModel)jTable1.getModel();
        int rowIndex = jTable1.getSelectedRow();

        int selectIndex=jTable1.getSelectedRow();

        txtsname.setText(d1.getValueAt(selectIndex, 1).toString());
        txtfname.setText(d1.getValueAt(selectIndex, 2).toString());
        txtphone.setText(d1.getValueAt(selectIndex, 3).toString());
        txtdob.setDate((Date) d1.getValueAt(selectIndex, 4));
        txtgender.setSelectedItem(d1.getValueAt(selectIndex, 5).toString()); // Assuming txtgender is a JComboBox
        txtclass.setText(d1.getValueAt(selectIndex, 6).toString());; // Assuming txtclass is a JComboBox
        txtsectionn.setSelectedItem(d1.getValueAt(selectIndex, 7).toString()); // Assuming txtsectionn is a JComboBox
        txtadddate.setDate((Date) d1.getValueAt(selectIndex, 8));
        txtcnic.setText(d1.getValueAt(selectIndex, 9).toString());
        txtemail.setText(d1.getValueAt(selectIndex, 10).toString());
        txtaddress.setText(d1.getValueAt(selectIndex, 11).toString());*/

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed
     
    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased

    }//GEN-LAST:event_txtemailKeyReleased
       
    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        JFrame frame = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame,"Do You Wish exit?","EXIT",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0); 
            
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   
    // Update Button Action
    DefaultTableModel d1 = (DefaultTableModel) jTable1.getModel();
    int selectedIndex = jTable1.getSelectedRow();

    if (selectedIndex == -1) {
        JOptionPane.showMessageDialog(null, "Select a record to update!");
        return;
    }

    // Assuming you have declared txtsname, txtfname, txtphone, txtdob, txtgender, txtclass,
    // txtsectionn, txtadddate, txtcnic, txtemail, and txtaddress earlier in your class.

    int id = Integer.parseInt(d1.getValueAt(selectedIndex, 0).toString());

    String candidateName = txtsname.getText();
    String fatherName = txtfname.getText();
    String mobile = txtphone.getText();
   
    // Assuming txtdob is a JDateChooser (date picker)
    Date dob = txtdob.getDate();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String dobStr = dateFormat.format(dob);

    String gender = txtgender.getSelectedItem().toString();
    String brNb = txtclass.getText();

    // Assuming txtsectionn is a JComboBox
    String section = txtsectionn.getSelectedItem().toString();
         
    // Assuming txtadddate is a JDateChooser (date picker)
    Date addDate = txtadddate.getDate();
    String addDateStr = dateFormat.format(addDate);

    String cnic = txtcnic.getText();
    String email = txtemail.getText();
    String address = txtaddress.getText();

    try {
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/simple_student", "root", "");

        String updateQuery = "UPDATE student SET studentname=?, fathername=?, phone=?, dateofbirth=?, gender=?, class=?, section=?, admissiondate=?, cnic=?, email=?, address=? WHERE id=?";
        PreparedStatement pst = con.prepareStatement(updateQuery);
         
        pst.setString(1, candidateName);
        pst.setString(2, fatherName);
        pst.setString(3, mobile);
        pst.setString(4, dobStr);
        pst.setString(5, gender);
        pst.setString(6, brNb);
        pst.setString(7, section);
        pst.setString(8, addDateStr);
        pst.setString(9, cnic);
        pst.setString(10, email);
        pst.setString(11, address);
        pst.setInt(12, id);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Candidate Updated Successfully!");
        table_update();
        clearFields();
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(database.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
}

private void clearFields() {
    txtsname.setText("");
    txtfname.setText("");
    txtphone.setText("");
    txtdob.setDate(null);
   // txtgender.setSelectedIndex(0);
    txtclass.setText("");
   // txtsectionn.setSelectedIndex(0);
    txtadddate.setDate(null);
    txtcnic.setText("");
    txtemail.setText("");
    txtaddress.setText("");
    txtsname.requestFocus();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        
        
        //Delete Button
        DefaultTableModel d1=(DefaultTableModel)jTable1.getModel();
        int selectIndex=jTable1.getSelectedRow();
         
        int id=Integer.parseInt(d1.getValueAt(selectIndex,0).toString());
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do you want delete the Record","Warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult ==JOptionPane.YES_OPTION)
        {  
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/simple_student","root","");
                pst=con.prepareStatement("delete from student where id=? ");
                pst.setInt(1,id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Candidate Deleted");
                table_update();
                /* txtbrand.setText("");
                txtstatus.setSelectedIndex(0);
                txtbrand.requestFocus();*/
                txtsname.setText("");
                txtfname.setText("");
                txtphone.setText("");
                txtdob.setDate(null);
                txtgender.setSelectedIndex(0);
                txtclass.setText("");
                txtsectionn.setSelectedIndex(0);
                txtadddate.setDate(null);
                txtcnic.setText("");
                txtemail.setText("");
                txtaddress.setText("");
                txtsname.requestFocus();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(database.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(database.class.getName()).log(Level.SEVERE, null, ex);
            }
             
        }

        /* DefaultTableModel d1=(DefaultTableModel)jTable1.getModel();
        int selectIndex=jTable1.getSelectedRow();

        int id=Integer.parseInt(d1.getValueAt(selectIndex,0).toString());
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do you want delete the Record","Warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult ==JOptionPane.YES_OPTION)
        {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/superpos","root","");
                pst=con1.prepareStatement("delete from product where id=? ");
                pst.setInt(1,id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Product Deleted");
                table_update();
                txtpro.setText("");
                txtpro.setText("");
                txtdesc.setText("");
                txtcat.setSelectedIndex(-1);
                txtbrand.setSelectedIndex(-1);
                txtcostp.setText("");
                txtretailp.setText("");
                txtqty.setText("");
                txtbarcode.setText("");
                txtstatus.setSelectedIndex(-1);
                txtpro.requestFocus();

                txtstatus.setSelectedIndex(-1);
                txtpro.requestFocus();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyPressed
        // TODO add your handling code here:
          char c =evt.getKeyChar();
        if(Character.isLetter(c))
        {
            //txtphone.setEditable(false);
            JOptionPane.showMessageDialog(null, "Invalid.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {   
            txtphone.setEditable(true);
        }
    }//GEN-LAST:event_txtphoneKeyPressed
                     
    private void txtphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyTyped
        // TODO add your handling code here:
         // phn nb validating

        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txtphone.getText().length() >= 10) {
            evt.consume(); // Ignore input if it's not a digit or exceeds 10 characters
            if (txtphone.getText().length() >= 10) {
                JOptionPane.showMessageDialog(null, "Only 10-digit phone numbers allowed", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtphoneKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel l_date;
    private javax.swing.JLabel l_time;
    private com.toedter.calendar.JDateChooser txtadddate;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtclass;
    private javax.swing.JTextField txtcnic;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JComboBox<String> txtgender;
    private javax.swing.JTextField txtphone;
    private javax.swing.JComboBox<String> txtsectionn;
    private javax.swing.JTextField txtsname;
    // End of variables declaration//GEN-END:variables
}
